#!/bin/bash

docker run -p=4000:4000 \
           -e EPHEMER_SERVICE=${SERVICE}:launch \
           -e EPHEMER_APIKEY=${EPHEMER_APIKEY} \
           -e EPHEMER_SECRET=${EPHEMER_SECRET} \
           -e EPHEMER_URL=${EPHEMER_URL} \
           -e EPHEMER_TOKEN=${EPHEMER_TOKEN} \
           ${DOCKER_IMG}

